name: CI

on:
  push:
    branches-ignore:
      - gh-pages
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'
    - cron: '15 18 * * *'
    - cron: '15 21 * * *'

concurrency:
  group: ${{ github.workflow }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ secrets.CODE_REPO }}
          token: ${{ secrets.CODE_TOKEN }}
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip

      - name: Install requirements
        run: pip3 install -r requirements.txt

      - name: Run code
        run: python3 run.py ${{ secrets.GITHUB_TOKEN }} ${{ secrets.API_URL }} ${{ secrets.API_TOKEN }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          BRANCH: gh-pages
          FOLDER: deploy/
          CLEAN: true
